environment:
  matrix:
  - configuration: Debug
  - configuration: Release

# branches to build
branches:
  # whitelist
  only:
    - develop

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\osrm

platform: x64

install:
  # by default, all script lines are interpreted as batch
  - cd c:\projects\osrm
  - curl -O http://build.project-osrm.org/libs_osrm_%Configuration%.7z
  - 7z x libs_osrm_%Configuration%.7z | find ":"

build_script:
  - cd c:/projects/osrm
  - mkdir build
  - cd build
  - echo Running cmake...
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - SET P=c:/projects/osrm
  - set TBB_INSTALL_DIR=%P%/tbb
  - set TBB_ARCH_PLATFORM=intel64/vc12
  - cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%Configuration% -DBZIP2_INCLUDE_DIR=%P%/libs/include -DBZIP2_LIBRARIES=%P%/libs/lib/libbz2.lib -DCMAKE_INSTALL_PREFIX=%P%/libs -DBOOST_ROOT=%P%/boost_min -DBoost_USE_STATIC_LIBS=ON
  - nmake
  - nmake tests
  - nmake benchmarks
  - if "%APPVEYOR_REPO_BRANCH%"=="develop" (7z a %P%/osrm_%Configuration%.zip *.exe *.pdb %P%/libs/bin/*.dll -tzip)
  - set PATH=%PATH%;c:/projects/osrm/libs/bin
  - cd c:/projects/osrm/build
  - datastructure-tests.exe

test: off

artifacts:
  - path: osrm_Debug.zip
    name: osrm_Debug.zip
  - path: osrm_Release.zip
    name: osrm_Release.zip

deploy:
  provider: FTP
  server:
    secure: ef7oiQTTXFGt8NdNiOHm/uRFVrUttzyFbIlnaeHhQvw=
  username:
    secure: Bw+Se2GTJxA6+GtRkEc//tQSBHOuFIuJHBjFwR9cD+8=
  password:
    secure: eqwESZqxMXC/j5mOCpaXuw==
  folder: /
  enable_ssl: true
  active_mode: false

# notifications:
#   - provider: HipChat
#     auth_token:
#       secure: boLE7BjcahdIUxv9jkN7U3F8iOASF+MkhtctlVoWJoo=
#     room: Directions
